//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackberry.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int IdItem { get; set; }
        public Nullable<int> IdProduct { get; set; }
    }
}
