//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackberry.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Swap
    {
        public int IdSwap { get; set; }
        public int IdProduct { get; set; }
        public Nullable<decimal> Count { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int IdUser { get; set; }
    }
}
